### ISSUE TITLE
Cannot POST to kestrel-server with Github Payload

### ISSUE THREAD

**Issue by aboutaaron** [mhkeller/kestrel#10]
POST
```bash
$ curl -X POST http://$SERVER-URL:9001 -d '$PAYLOAD'
```

SERVER RESPONSE:
```bash
Listening on port... 9001
Error: Invalid ref
    at /home/edsys/kestrel/node_modules/hookshot/lib/index.js:28:13
    at Layer.handle [as handle_request] (/home/edsys/kestrel/node_modules/hookshot/node_modules/express/lib/router/layer.js:82:5)
    at next (/home/edsys/kestrel/node_modules/hookshot/node_modules/express/lib/router/route.js:100:13)
    at Route.dispatch (/home/edsys/kestrel/node_modules/hookshot/node_modules/express/lib/router/route.js:81:3)
    at Layer.handle [as handle_request] (/home/edsys/kestrel/node_modules/hookshot/node_modules/express/lib/router/layer.js:82:5)
    at /home/edsys/kestrel/node_modules/hookshot/node_modules/express/lib/router/index.js:234:24
    at Function.proto.process_params (/home/edsys/kestrel/node_modules/hookshot/node_modules/express/lib/router/index.js:312:12)
    at /home/edsys/kestrel/node_modules/hookshot/node_modules/express/lib/router/index.js:228:12
    at Function.match_layer (/home/edsys/kestrel/node_modules/hookshot/node_modules/express/lib/router/index.js:295:3)
    at next (/home/edsys/kestrel/node_modules/hookshot/node_modules/express/lib/router/index.js:189:10)
```

Payload:
```json
{
  "ref": "refs/heads/master",
  "before": "0000000000000000000000000000000000000000",
  "after": "340a2a14d737ae0ee92e8047d448acd34699ced0",
  "created": true,
  "deleted": false,
  "forced": true,
  "base_ref": null,
  "compare": "https://github.com/sfchronicle/test-project/commit/340a2a14d737",
  "commits": [
    {
      "id": "340a2a14d737ae0ee92e8047d448acd34699ced0",
      "distinct": true,
      "message": "initial commit",
      "timestamp": "2015-08-20T12:10:14-07:00",
      "url": "https://github.com/sfchronicle/test-project/commit/340a2a14d737ae0ee92e8047d448acd34699ced0",
      "author": {
        "name": "Aaron Williams",
        "email": "aaron.colby.williams@gmail.com",
        "username": "aboutaaron"
      },
      "committer": {
        "name": "Aaron Williams",
        "email": "aaron.colby.williams@gmail.com",
        "username": "aboutaaron"
      },
      "added": [
        ".bowerrc",
        ".editorconfig",
        ".gitattributes",
        ".gitignore",
        ".jshintrc",
        ".yo-rc.json",
        "Gruntfile.js",
        "README.md",
        "app/favicon.ico",
        "app/index.html",
        "app/robots.txt",
        "app/scripts/main.js",
        "app/styles/main.scss",
        "bower.json",
        "package.json",
        "test/.bowerrc",
        "test/bower.json",
        "test/index.html",
        "test/spec/test.js"
      ],
      "removed": [

      ],
      "modified": [

      ]
    }
  ],
  "head_commit": {
    "id": "340a2a14d737ae0ee92e8047d448acd34699ced0",
    "distinct": true,
    "message": "initial commit",
    "timestamp": "2015-08-20T12:10:14-07:00",
    "url": "https://github.com/sfchronicle/test-project/commit/340a2a14d737ae0ee92e8047d448acd34699ced0",
    "author": {
      "name": "Aaron Williams",
      "email": "aaron.colby.williams@gmail.com",
      "username": "aboutaaron"
    },
    "committer": {
      "name": "Aaron Williams",
      "email": "aaron.colby.williams@gmail.com",
      "username": "aboutaaron"
    },
    "added": [
      ".bowerrc",
      ".editorconfig",
      ".gitattributes",
      ".gitignore",
      ".jshintrc",
      ".yo-rc.json",
      "Gruntfile.js",
      "README.md",
      "app/favicon.ico",
      "app/index.html",
      "app/robots.txt",
      "app/scripts/main.js",
      "app/styles/main.scss",
      "bower.json",
      "package.json",
      "test/.bowerrc",
      "test/bower.json",
      "test/index.html",
      "test/spec/test.js"
    ],
    "removed": [

    ],
    "modified": [

    ]
  },
  "repository": {
    "id": 41114129,
    "name": "test-project",
    "full_name": "sfchronicle/test-project",
    "owner": {
      "name": "sfchronicle",
      "email": ""
    },
    "private": true,
    "html_url": "https://github.com/sfchronicle/test-project",
    "description": null,
    "fork": false,
    "url": "https://github.com/sfchronicle/test-project",
    "forks_url": "https://api.github.com/repos/sfchronicle/test-project/forks",
    "keys_url": "https://api.github.com/repos/sfchronicle/test-project/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/sfchronicle/test-project/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/sfchronicle/test-project/teams",
    "hooks_url": "https://api.github.com/repos/sfchronicle/test-project/hooks",
    "issue_events_url": "https://api.github.com/repos/sfchronicle/test-project/issues/events{/number}",
    "events_url": "https://api.github.com/repos/sfchronicle/test-project/events",
    "assignees_url": "https://api.github.com/repos/sfchronicle/test-project/assignees{/user}",
    "branches_url": "https://api.github.com/repos/sfchronicle/test-project/branches{/branch}",
    "tags_url": "https://api.github.com/repos/sfchronicle/test-project/tags",
    "blobs_url": "https://api.github.com/repos/sfchronicle/test-project/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/sfchronicle/test-project/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/sfchronicle/test-project/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/sfchronicle/test-project/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/sfchronicle/test-project/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/sfchronicle/test-project/languages",
    "stargazers_url": "https://api.github.com/repos/sfchronicle/test-project/stargazers",
    "contributors_url": "https://api.github.com/repos/sfchronicle/test-project/contributors",
    "subscribers_url": "https://api.github.com/repos/sfchronicle/test-project/subscribers",
    "subscription_url": "https://api.github.com/repos/sfchronicle/test-project/subscription",
    "commits_url": "https://api.github.com/repos/sfchronicle/test-project/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/sfchronicle/test-project/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/sfchronicle/test-project/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/sfchronicle/test-project/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/sfchronicle/test-project/contents/{+path}",
    "compare_url": "https://api.github.com/repos/sfchronicle/test-project/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/sfchronicle/test-project/merges",
    "archive_url": "https://api.github.com/repos/sfchronicle/test-project/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/sfchronicle/test-project/downloads",
    "issues_url": "https://api.github.com/repos/sfchronicle/test-project/issues{/number}",
    "pulls_url": "https://api.github.com/repos/sfchronicle/test-project/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/sfchronicle/test-project/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/sfchronicle/test-project/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/sfchronicle/test-project/labels{/name}",
    "releases_url": "https://api.github.com/repos/sfchronicle/test-project/releases{/id}",
    "created_at": 1440097773,
    "updated_at": "2015-08-20T19:09:33Z",
    "pushed_at": 1440097820,
    "git_url": "git://github.com/sfchronicle/test-project.git",
    "ssh_url": "git@github.com:sfchronicle/test-project.git",
    "clone_url": "https://github.com/sfchronicle/test-project.git",
    "svn_url": "https://github.com/sfchronicle/test-project",
    "homepage": null,
    "size": 0,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": null,
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master",
    "stargazers": 0,
    "master_branch": "master",
    "organization": "sfchronicle"
  },
  "pusher": {
    "name": "aboutaaron",
    "email": "aaron.colby.williams@gmail.com"
  },
  "organization": {
    "login": "sfchronicle",
    "id": 12716373,
    "url": "https://api.github.com/orgs/sfchronicle",
    "repos_url": "https://api.github.com/orgs/sfchronicle/repos",
    "events_url": "https://api.github.com/orgs/sfchronicle/events",
    "members_url": "https://api.github.com/orgs/sfchronicle/members{/member}",
    "public_members_url": "https://api.github.com/orgs/sfchronicle/public_members{/member}",
    "avatar_url": "https://avatars.githubusercontent.com/u/12716373?v=3",
    "description": "Code from the San Francisco Chronicle Interactive Desk"
  },
  "sender": {
    "login": "aboutaaron",
    "id": 856628,
    "avatar_url": "https://avatars.githubusercontent.com/u/856628?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/aboutaaron",
    "html_url": "https://github.com/aboutaaron",
    "followers_url": "https://api.github.com/users/aboutaaron/followers",
    "following_url": "https://api.github.com/users/aboutaaron/following{/other_user}",
    "gists_url": "https://api.github.com/users/aboutaaron/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/aboutaaron/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/aboutaaron/subscriptions",
    "organizations_url": "https://api.github.com/users/aboutaaron/orgs",
    "repos_url": "https://api.github.com/users/aboutaaron/repos",
    "events_url": "https://api.github.com/users/aboutaaron/events{/privacy}",
    "received_events_url": "https://api.github.com/users/aboutaaron/received_events",
    "type": "User",
    "site_admin": false
  }
}
```

**Comment by aboutaaron** [comment]
Worth, noting, the server is an Ubuntu 14.04 box on Amazon EC2 and the Github IP range is white listed in our security group.

I can `curl` just fine from within our firewall, but Github cannot POST to the server and returns a `Service Timeout` error

**Comment by mhkeller** [comment]
I put some better error reporting to see what it thinks `payload.ref` is. quick and dirty update

```
cd node_modules/hookshot
git pull origin master
node src/server.js
```

and redo your local curl to see what it prints out as payload.ref. if it's `undefined` then something is also happening to the payload. maybe throw a `console.log(payload)` in there for good measure.

**Comment by mhkeller** [comment]
this is the change btw

https://github.com/mhkeller/hookshot/commit/4cd4ad80a5f31577ffcd2845510d4bac0a57cb66

**Comment by aboutaaron** [comment]
## update
Looks like I got the payload to deliver. Part of the issue was that my `curl` argument syntax was off. Another issue was I didn't specify a content type. After adjusting those, the server returned:
```bash
## Incoming push from sfchronicle
Checking if deploy message in... initial commit
Deploy status is false
Creating folder and git repository...
cd repositories/test-project && git init && git remote add origin https://aff90979a7bee4a9901cb5cccdedb408afc55964@github.com/sfchronicle/test-project
Initialized empty Git repository in /home/edsys/kestrel/repositories/test-project/.git/
Git created!
remote: Counting objects: 26, done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 26 (delta 0), reused 26 (delta 0), pack-reused 0
Unpacking objects: 100% (26/26), done.
From https://github.com/sfchronicle/test-project
 * [new branch]      master     -> origin/master
Branch master set up to track remote branch master from origin.
Already on 'master'
From https://github.com/sfchronicle/test-project
 * branch            master     -> FETCH_HEAD
Already up-to-date.
Already on 'master'
Your branch is up-to-date with 'origin/master'.
express deprecated res.send(status, body): Use res.status(status).send(body) instead node_modules/hookshot/lib/index.js:40:9
```

I resent the payload from Github with no luck, meaning that this looks like a security group problem. I'll close this issue for now but keep looking for a workaround for the security group problem and will report back. Thanks!

**Comment by mhkeller** [comment]
Maybe double-check the ip address of the kestrel box in the webhook is correct and not https. Mine looks like

````
 "url": "http://<foo>.<bar>.<baz>.<banana>:9001"
````
